Add function and documentation to draw circle
python-pillow/Pillow pull request #8085
Opened 2024-05-26 22:24 UTC by void4

Implements the ImageDraw.circle feature as described and desired in https://github.com/python-pillow/Pillow/issues/8083

2024-05-26 23:40 UTC, Yay295 commented on src/PIL/ImageDraw.py
> +            self.draw.draw_ellipse(ellipse_xy, ink, 0, width)
These four lines could be replaced by just `self.ellipse(ellipse_xy, fill, outline, width)`, and you can then remove the first line of code as well.

2024-05-27 04:33 UTC, hugovk requested changes
Please could you add unit tests, and mention this in the release notes?

2024-05-27 04:33 UTC, hugovk commented on docs/reference/ImageDraw.rst
> +        .. versionadded:: ?.?.?
```suggestion
        .. versionadded:: 10.4.0
```

2024-05-27 11:15 UTC, hugovk commented on docs/reference/ImageDraw.rst
> +    Draws a circle given the center coordinates and a radius.
Let's move this up to indicate the function is new:
```suggestion
    Draws a circle given the center coordinates and a radius.
    
    .. versionadded:: 10.4.0
```

2024-05-27 11:15 UTC, hugovk commented on docs/reference/ImageDraw.rst
> +
And not the `width` param:
```suggestion
```

2024-05-27 11:25 UTC, radarhere commented on src/PIL/ImageDraw.py
> +    def circle(self, xy: Coords, radius, fill=None, outline=None, width=1) -> None:
```suggestion
    def circle(
        self, xy: Sequence[float], radius: float, fill=None, outline=None, width=1
    ) -> None:
```
`Coords` is either a sequence or a sequence of a sequence. Here, you just want a sequence.
https://github.com/python-pillow/Pillow/blob/bbe1effd63149eb3d43d59efb5fe2659f93700d0/src/PIL/_typing.py#L20

2024-05-27 11:39 UTC, void4 commented
> Please could you add unit tests, and mention this in the release notes?

I've added it to the release notes but am not quite sure how the unit tests work, especially the parametrization :/

2024-05-27 16:28 UTC, void4 commented
Thank you - merged :)

2024-05-27 22:14 UTC, radarhere approved these changes

2024-05-28 09:35 UTC, merged

2024-05-28 09:35 UTC, hugovk commented
Thank you!