Fixed a bug with channel 4 population in ImageQt.py
python-pillow/Pillow pull request #8507
Opened 2024-10-26 09:36 UTC by codev8services

Changes proposed in this pull request:

1. Fixed a bug with channel 4 population and format inconsistencies: lines 164, 167.
2. Added PyQt5 support.

The changes have been tested.

2024-10-26 09:42 UTC, radarhere commented
Hi. We deliberately deprecated support for PyQt5 in Pillow 9.2.0 - https://pillow.readthedocs.io/en/stable/releasenotes/9.2.0.html#pyqt5-and-pyside2

> [Qt 5 reached end-of-life](https://www.qt.io/blog/qt-5.15-released) on 2020-12-08 for open-source users (and will reach EOL on 2023-12-08 for commercial licence holders).
> 
> Support for PyQt5 and PySide2 has been deprecated from ImageQt and will be removed in Pillow 10 (2023-07-01). Upgrade to [PyQt6](https://www.riverbankcomputing.com/static/Docs/PyQt6/) or [PySide6](https://doc.qt.io/qtforpython-6/) instead.

Support was removed on schedule in Pillow 10.

Could you provide more information about your 'bug with channel 4 population and format inconsistencies'? Is this a problem that only happens with PyQt5, or with PyQt6 as well? Could you provide a short code snippet to demonstrate the problem?

2024-10-26 11:31 UTC, codev8services commented
No, I have managed to reproduce this issue in both PyQt5 and PyQt6.

The corrections I made to the code resolved the issue. Although PyQt5 was not necessary for the original problem, its support was straightforward to implement. I used it to replicate the issue repeatedly.

```
from PyQt6.QtWidgets import QPushButton, QListWidget, QWidget, QApplication, QLabel, QVBoxLayout
from PyQt6.QtCore import Qt

#* The problem is also reproduced in the example using PyQt5.
# from PyQt5.QtWidgets import QPushButton, QListWidget, QWidget, QApplication, QLabel, QVBoxLayout
# from PyQt5.QtCore import Qt

from PIL import Image, ImageQt


def load_img():

    # The problem only occurs with RGB images, 
    # as indicated in the changes that I suggested.

    img = Image.open("cat.jpg")
    
    # The RGB image causes the program to crash with no obvious error in the console, 
    # or it loads in an incorrect format (I have attached a screenshot).
    pixmap = ImageQt.toqpixmap(img)

    picture_view.setPixmap(pixmap)


app = QApplication([])
window = QWidget()
window.resize(700, 600)

btn = QPushButton('load image to pixmap')
picture_view = QLabel('Image View')
picture_view.setStyleSheet("background: magenta")

layout = QVBoxLayout(window)
layout.addWidget(btn)
layout.addWidget(picture_view)

btn.clicked.connect(load_img)

window.show()
app.exec()
```

ERROR
![error](https://github.com/user-attachments/assets/3834f5a1-807f-4cd7-ad3d-dbbfc82e8646)

CORRECT
![correct](https://github.com/user-attachments/assets/4cb765b9-e540-4946-b0b2-00d038456be9)

2024-10-26 11:37 UTC, radarhere commented
Could you provide a copy of cat.jpg?

What operating system are you using? What version of PyQt6?

```pycon
>>> from PyQt6.QtCore import QT_VERSION_STR, PYQT_VERSION_STR
>>> print("Qt: v", QT_VERSION_STR, "\tPyQt: v", PYQT_VERSION_STR)
Qt: v 6.7.1 	PyQt: v 6.7.0
```

2024-10-26 11:50 UTC, codev8services commented
Qt: v 6.7.1     PyQt: v 6.7.1

Microsoft Windows [Version 10.0.17763.1697]
x64-based PC

I have tried to reproduce the error with other RGB images. In total, I have checked 4 images in the jpg format and there have been problems with all of them. However, there are no issues with the png format.

cat.jpg
![cat](https://github.com/user-attachments/assets/d14bd7d6-65a0-4156-84b0-b18438c3b336)

The picture was downloaded from the Freepik website.

2024-10-26 12:02 UTC, radarhere commented
Thanks. I'm unable to replicate your problem on my macOS machine - here's a screenshot using your image.

<img src="https://github.com/user-attachments/assets/55f7daf4-992e-4f89-9a25-84cd5c033edb" width="250" />

2024-10-26 12:10 UTC, codev8services commented
I also tested Pillow versions 10.0.0 and 9.5.0. 

The error was discovered during classes with my student (also Windows). It appeared on his PC, I was able to reproduce it on mine.

So, the issue has been present in multiple versions of Pillow and occurs on Windows machines.

2024-10-27 11:15 UTC, radarhere commented
I put together a [commit](https://github.com/radarhere/Pillow/commit/2109c0c943d9d841a1a6bb1b224b48fbef8a559e) to try and replicate this on GitHub Actions - it is indeed a problem on [Windows](https://github.com/radarhere/Pillow/actions/runs/11539930203)

<img src="https://github.com/user-attachments/assets/23eb95d4-9754-4ebf-b758-db8c4720dfb7" width="400" />

but not on [macOS](https://github.com/radarhere/Pillow/actions/runs/11539930206)

<img src="https://github.com/user-attachments/assets/cd94cc48-1381-4f05-bddc-56f1c1464ee8" width="400" />

This PR does indeed [fix the problem](https://github.com/radarhere/Pillow/actions/runs/11539934662)

<img src="https://github.com/user-attachments/assets/b9355427-6ff8-4b56-9b10-f44cbf1c32c6" width="400" />

2024-10-27 11:19 UTC, hugovk requested changes

2024-10-27 11:19 UTC, hugovk commented on src/PIL/ImageQt.py
> +    import PyQt5
Let's not re-add PyQt5:
```suggestion
```

2024-10-27 11:19 UTC, hugovk commented on src/PIL/ImageQt.py
> +    ["5", "PyQt5"],
```suggestion
```

2024-10-27 11:19 UTC, hugovk commented on src/PIL/ImageQt.py
> +            from PyQt5.QtGui import QImage, QPixmap, qRgba
```suggestion
```

2024-10-27 11:19 UTC, hugovk commented on src/PIL/ImageQt.py
> +        # Populate the 4th channel with 255 #!
```suggestion
        # Populate the 4th channel with 255
```

2024-10-27 11:19 UTC, hugovk commented on src/PIL/ImageQt.py
> +        format = getattr(qt_format, "Format_ARGB32") # 4th channel was populated in line 164
No need to repeat an earlier comment, and the line number will go out of sync:
```suggestion
        format = getattr(qt_format, "Format_ARGB32")
```

2024-10-28 13:19 UTC, radarhere commented
@codev8services you may have noticed that our test suite is failing here, because it doesn't expect RGB images to be turned into RGBA. I've come up with an alternative suggestion that lets us continue to use RGB. Would you mind testing #8509?

2024-10-29 11:07 UTC, radarhere commented
#8509 has now been merged instead.

2024-10-29 11:07 UTC, closed without merging